CREATE DATABASE IF NOT EXISTS ihunters;

USE ihunters;

CREATE TABLE IF NOT EXISTS persons(
	id INT NOT NULL AUTO_INCREMENT, 
	name TEXT NOT NULL, 
	PRIMARY KEY (id),
	UNIQUE (name(1024))
	);

CREATE TABLE IF NOT EXISTS sites(
	id INT NOT NULL AUTO_INCREMENT, 
	name NVARCHAR(256) NOT NULL UNIQUE, 
	PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS keywords (
	id INT NOT NULL AUTO_INCREMENT, 
	name TEXT NOT NULL, 
	person_id INT NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY (person_id) 
		REFERENCES persons(id) 
		ON DELETE CASCADE,
	UNIQUE (name(1024))
	);

CREATE TABLE IF NOT EXISTS pages(
	id INT NOT NULL AUTO_INCREMENT, 
	url TEXT NOT NULL, 
	site_id INT NOT NULL, 
	found_date_time DATETIME DEFAULT CURRENT_TIMESTAMP, 
	last_scan_date DATETIME ON UPDATE CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	FOREIGN KEY (site_id) 
		REFERENCES sites(id) 
		ON DELETE CASCADE,
	UNIQUE (url(1024))
	);

CREATE TABLE IF NOT EXISTS person_page_rank(
	person_id INT NOT NULL, 
	page_id INT NOT NULL, 
	rank INT NOT NULL, 
	FOREIGN KEY (person_id) 
		REFERENCES persons(id) 
		ON DELETE CASCADE, 
	FOREIGN KEY (page_id) 
		REFERENCES pages(id) 
		ON DELETE CASCADE);